name: todo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduced:
    path: ../../
  inherited_widgets:
    path: ../../inherited_widgets
  reduced_binder:
    path: ../../approaches/reduced_binder
  reduced_bloc:
    path: ../../approaches/reduced_bloc
  reduced_fluttercommand:
    path: ../../approaches/reduced_fluttercommand
  reduced_fluttertriple:
    path: ../../approaches/reduced_fluttertriple
  reduced_getit:
    path: ../../approaches/reduced_getit
  reduced_getx:
    path: ../../approaches/reduced_getx
  reduced_mobx:
    path: ../../approaches/reduced_mobx
  reduced_provider:
    path: ../../approaches/reduced_provider
  reduced_redux:
    path: ../../approaches/reduced_redux
  reduced_riverpod:
    path: ../../approaches/reduced_riverpod
  reduced_solidart:
    path: ../../approaches/reduced_solidart
  reduced_setstate:
    path: ../../approaches/reduced_setstate
  reduced_statesrebuilder:
    path: ../../approaches/reduced_statesrebuilder
  flutter_riverpod: ^2.1.3
  flutter_bloc: ^8.1.1
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  provider: ^6.0.5
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4+2
  get: ^4.6.5
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  solidart: ^0.1.2
  flutter_solidart: ^0.1.4
  states_rebuilder: ^6.2.0
  flutter_triple: ^1.2.7+4
  binder: ^0.4.0
  flutter_command: ^2.0.1
  fish_redux: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.22.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
