name: example
description: Example app for the state management API 'reduced'.
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduced: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
