name: shopper_app
description: porting the shopper sample application from the Flutter documentation using the 'Provider' state management framework via the 'reduced' API and the 'reduced_provider' implementation as an example of how to use the 'reduced' package.
publish_to: none

version: 0.4.1+4

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reduced: 0.4.1
#  reduced: 
#    git: 
#      url: https://github.com/partmaster/reduced.git
#      ref: v0.4.1-beta.4
  reduced_provider: 
    git: 
      url: https://github.com/partmaster/reduced_provider.git
      ref: v0.4.1
  go_router: ^6.0.0
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
#  analysis_defaults:
#    path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
