name: counter_app
description: Counter demo app implemented with 'reduced' API and 'reduced_bloc' implementation as an example of the usage of the 'reduced' package.
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    git: 
      url: https://github.com/partmaster/reduced.git
      ref: main
  reduced_bloc: 
    git: 
      url: https://github.com/partmaster/reduced_bloc.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
