name: counter_app
description: Counter demo app implemented with 'reduced' API and 'reduced_bloc' implementation as an example of how to use the 'reduced' package.
publish_to: 'none' 
version: 0.3.2+5

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  reduced: 0.3.2
  reduced_bloc: 
    git: 
      url: https://github.com/partmaster/reduced_bloc.git
      ref: v0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
